// Bahrain areas by district. Copied from models/areas.py in the backend
export const AREAS_BY_DISTRICT = {
  capital: [
    "Manama",
    "Adliya",
    "Diplomatic Area",
    "Gudaibiya",
    "Hoora",
    "Jid Ali",
    "Juffair",
    "Ras Rumman",
    "Sanabis",
    "Sanad",
    "Seef",
    "Sitra",
    "Tubli",
    "Zinj",
    "Jidhafs",
  ],
  muharraq: [
    "Muharraq",
    "Al Dair",
    "Al Hidd",
    "Amwaj Islands",
    "Arad",
    "Busaiteen",
    "Diyar Al Muharraq",
    "Galali",
    "Halat Bu Maher",
    "Samaheej",
  ],
  northern: [
    "A'ali",
    "Abu Saiba",
    "Al Hajar",
    "Al Markh",
    "Al Qadam",
    "Al Qala",
    "Barbar",
    "Boori",
    "Budaiya",
    "Buquwa",
    "Dar Kulaib",
    "Diraz",
    "Dumistan",
    "Hamad Town",
    "Hamala",
    "Hillat Abdul Saleh",
    "Janabiya",
    "Jannusan",
    "Jasra",
    "Jid Al-Haj",
    "Karrana",
    "Karzakan",
    "Malikiya",
    "Muqaba",
    "North Sehla",
    "Northern City",
    "Qurayya",
    "Saar",
    "Sadad",
    "Salmabad",
    "Shahrakan",
    "Shakhura",
    "Umm an Nasan",
    "Umm as Sabaan",
    "Zayed City",
  ],
  southern: [
    "Riffa",
    "Al Dur",
    "Askar",
    "Awali",
    "Durrat Al Bahrain",
    "Hawar Islands",
    "Isa Town",
    "Jaww",
    "Khalifa City",
    "Ma'ameer",
    "Sakhir",
    "Zallaq",
  ],
};

export const areasFor = district => AREAS_BY_DISTRICT[district] || [];
